type Position @entity {
  id: ID!
  positionId: BigInt!
  trader: Bytes!
  pairId: Bytes!
  isLong: Boolean!
  sizeUsd: BigInt!
  entryPrice: BigInt!
  leverage: BigInt!
  collateral: BigInt!
  liquidationPrice: BigInt!
  isOpen: Boolean!
  openedAt: BigInt!
  closedAt: BigInt
  exitPrice: BigInt
  pnl: BigInt
  tpPrice: BigInt
  slPrice: BigInt
}

type Order @entity {
  id: ID!
  orderId: BigInt!
  trader: Bytes!
  pairId: Bytes!
  orderType: Int!
  triggerPrice: BigInt!
  sizeUsd: BigInt!
  leverage: BigInt!
  collateral: BigInt!
  isLong: Boolean!
  isActive: Boolean!
  createdAt: BigInt!
  executedAt: BigInt
  positionId: BigInt
  tpPrice: BigInt
  slPrice: BigInt
  twapSlices: BigInt
  twapExecuted: BigInt
}

type TradeRecord @entity {
  id: ID!
  trader: Bytes!
  pairId: Bytes!
  isLong: Boolean
  action: String! # "Open", "Close", "Liquidate", "PartialClose", "Increase", "AddCollateral", "RemoveCollateral"
  sizeUsd: BigInt!
  price: BigInt!
  pnl: BigInt
  timestamp: BigInt!
  txHash: Bytes!
}

type VaultDeposit @entity {
  id: ID!
  user: Bytes!
  action: String! # "deposit" or "withdraw"
  amount: BigInt!
  shares: BigInt!
  isDegen: Boolean!
  timestamp: BigInt!
  txHash: Bytes!
}

type PairDayData @entity {
  id: ID! # pairId-dayId
  pairId: Bytes!
  date: Int! # dayId * 86400
  volumeUsd: BigInt!
}


type PairStat @entity {
  id: ID!
  longOI: BigInt!
  shortOI: BigInt!
}

type VaultStat @entity {
  id: ID!
  tvlUsdc: BigInt!
  totalShares: BigInt!
}

type TraderStat @entity {
  id: ID! # trader address
  trader: Bytes!
  totalProfit: BigInt!
  totalLoss: BigInt!
  netPnl: BigInt!
  totalVolume: BigInt!
  tradesCount: Int!
  winCount: Int!
}

